version: '3.8'
services:
  postgres:
    container_name: patient-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5000:5432"
    volumes:
      - C:\Users\pc\db_volumes\patient-service-db:/var/lib/postgresql/data
  backend:
    container_name: patient-api
    image: patient-service-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_SQL_INIT_MODE=always
    ports:
      - "4000:4000"
    depends_on:
      - postgres
